#
# Publishes a Docker image.
#

set -u # or set -o nounset
: "$ECR_REPOSITORY1"
: "$ECR_REPOSITORY2"
: "$ECR_REGISTRY"
: "$VERSION"

docker tag $ECR_REPOSITORY1:latest $ECR_REGISTRY/$ECR_REPOSITORY1:$VERSION
docker tag $ECR_REPOSITORY2:latest $ECR_REGISTRY/$ECR_REPOSITORY2:$VERSION
docker push $ECR_REGISTRY/$ECR_REPOSITORY1:$VERSION
docker push $ECR_REGISTRY/$ECR_REPOSITORY2:$VERSION
